pizza/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.PizzaList.as_view(),
         name='order_url'),
    path("order/<int:id>/",
         views.order_pizza,
         name='order_pizza'),
    path("my_orders/",
         views.my_orders,
         name='my_orders'),
    path("delete_order/<int:id>/",
         views.delete_pizza_order,
         name='delete_pizza_order'),
    path("update_pizza_quantity/<int:item_id>/",
         views.update_pizza_quantity,
         name='update_pizza_quantity'),
    path('contact_us/',
         views.contact_us,
         name='contactus'),
    path("accounts/", include("allauth.urls"))]

pizza_me/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pizza/", include("pizza.urls"), name="pizza-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
    path("",
         include("pizza.urls"),
         name="order_url"),
]

pizza/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.

# MoSCoW Prioritization - Must Have


class Order(models.Model):
    """
    Stores a single order related to  :model:`auth.User`.
    """
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(
        "auth.User",
        verbose_name=("User_ID"),
        on_delete=models.CASCADE
        )
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=9,
        choices=[('Cart', 'Cart'),
                 ('Pending', 'Pending'),
                 ('Prepared', 'Prepared'),
                 ('Delivered', 'Delivered'),
                 ('Cancelled', 'Cancelled')]
        )
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    forward_order = models.BooleanField(
        default=False,
        choices=[(True, 'Yes'),
                 (False, 'No')]
        )
    forward_order_time = models.DateTimeField(auto_now_add=False)


class Pizza(models.Model):
    """
    stores a single pizza entry with the following fields:
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    size = models.CharField(
        max_length=6,
        choices=[('Small', 'Small'),
                 ('Medium', 'Medium'),
                 ('Large', 'Large')]
    )
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    enabled = models.BooleanField(
        default=False,
        choices=[(
            True, 'Yes'),
            (False, 'No')]
        )


class OrderItem(models.Model):
    """
    Stores the reference to the order and the
    pizza with the quantity ordered with the following fields:
    """
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(
        Order,
        verbose_name=("Order_ID"),
        on_delete=models.CASCADE
        )
    pizza_id = models.ForeignKey(
        Pizza,
        verbose_name=("Pizza_ID"),
        on_delete=models.CASCADE
        )
    quantity = models.PositiveIntegerField()


# MoSCoW Prioritization - Should Have
class Payment(models.Model):
    """
    Stores a single payment entry with the following fields:
    """
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(
        Order,
        verbose_name=("Order_ID"),
        on_delete=models.CASCADE
        )
    payment_method = models.CharField(
        max_length=12,
        choices=[('Credit Card', 'Credit Card'),
                 ('PayPal', 'PayPal'),
                 ('Cash', 'Cash')]
        )
    payment_status = models.CharField(
        max_length=8,
        choices=[('Paid', 'Paid'),
                 ('Pending', 'Pending'),
                 ('Failed', 'Failed')]
        )


class ContactUs(models.Model):
    """
    Stores a single contact request entry.
    """
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"Contact Us from {self.name}"

pizza/forms.py
from django import forms
from .models import ContactUs


class ContactUsForm(forms.ModelForm):
    """
    This class is used to create a form for the ContactUs model.
    **Context**
    ''fields''
        The fields of the form.
        `name` - The name of the person contacting
        `email` - The email of the person contacting
        `message` - The message of the person contacting
    """
    class Meta:
        model = ContactUs
        fields = ('name', 'email', 'message')

pizza/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Pizza, Order, OrderItem
from .forms import ContactUsForm

# Create your views here.


class PizzaList(generic.ListView):
    """
    Renders a list of Pizza's available for order.
    **Context**
    Displays an individual instance of :model:`pizza` for
    each pizza that has been created in the last 24 hours.
    The user must be authenticated to order a pizza,
    edit or delete their own orders.
    Items ordered (order_items) are stored in the user's
    cart (cart_order) until they are checked out.
    **Template:**
    :template:`pizza/order.html`
    """

    queryset = Pizza.objects.filter(enabled=True)
    template_name = "pizza/order.html"
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            today = timezone.now().date()
            cart_order = Order.objects.filter(user_id=self.request.user.id,
                                              status='Cart',
                                              order_date__date=today).first()
            if cart_order:
                order_items = cart_order.orderitem_set.filter(
                    order_id__order_date__date=today)
                context['order_items'] = order_items
            context['cart_order'] = cart_order
        return context


def index(request):
    return render(request, 'pizza/index.html')


def order(request):
    return render(request, 'pizza/order.html')


@login_required
def order_pizza(request, id):
    """
    Adds a pizza to the user's cart.
    **Context**
    The user must be authenticated to order a pizza,
    edit or delete their own orders. If an order has already been
    opened today, the pizza is added to the existing order.
    If the pizza is already in the order and the order button is pressed, the quantity is incremented.
    **Template:**
    :template:`pizza/order.html`
    """
    pizza = get_object_or_404(Pizza, id=id)

    # Check if an order has already been opened today
    today = timezone.now().date()
    existing_order = Order.objects.filter(
        user_id=request.user,
        forward_order_time__date=today).first()

    if existing_order:
        # If an order exists, check if the pizza is already in the order
        order_item = existing_order.orderitem_set.filter(
            pizza_id=pizza).first()
        if order_item:
            # Increment the quantity if the pizza is already in the order
            order_item.quantity += 1
            order_item.save()
            messages.success(
                request,
                'The quantity of the pizza in your order '
                'has been updated successfully.'
            )
        else:
            # Add the pizza to the existing order
            OrderItem.objects.create(
                order_id=existing_order,
                pizza_id=pizza,
                quantity=1
                )
            messages.success(
                request,
                'Your item has been added to your existing order successfully.'
            )
    else:
        # Create a new order
        order = Order.objects.create(
            user_id=request.user,
            total_price=pizza.price,
            status='Cart',
            forward_order_time=timezone.now()
            )
        OrderItem.objects.create(
            order_id=order,
            pizza_id=pizza,
            quantity=1
            )
        messages.success(
            request,
            'Your item has been added to your basket successfully.'
            )

    return HttpResponseRedirect(reverse('order_url'))


@login_required
def delete_pizza_order(request, id):
    """
    Deletes a pizza from the user's cart.
    **Context**
    The user must be authenticated to delete a pizza from their cart.
    If the pizza is not in the cart, the user is informed that the pizza
    cannot be deleted. If the pizza is in the cart, the pizza is deleted.
    **Template:**
    :template:`pizza/order.html`
    """
    today = timezone.now().date()
    order = Order.objects.filter(
        user_id=request.user,
        forward_order_time__date=today
    ).first()

    if not order:
        messages.error(request,
                       'No order on file, you haven\'t started your order yet.'
                       )
        return HttpResponseRedirect(reverse('order_url'))

    try:
        order_item_to_delete = OrderItem.objects.get(
            order_id=order,
            pizza_id=id
        )
    except OrderItem.DoesNotExist:
        messages.error(request,
                       'This pizza is not on your order to delete, '
                       'so you cannot delete it.'
                       )
        return HttpResponseRedirect(reverse('order_url'))

    if order.user_id == request.user:
        # Delete the specific OrderItem
        order_item_to_delete.delete()
        messages.success(request, 'Your pizza has been removed from '
                         'your basket successfully.')
    else:
        messages.error(request, 'You can only delete your own pizzas!')

    return HttpResponseRedirect(reverse('order_url'))


@login_required
def my_orders(request):
    """
    Renders a list of the user's orders.
    **Context**
    Allows the user to view their order history.
    The user must be authenticated to view their order history.
    **Template:**
    :template:`pizza/my_orders.html`
    """
    orders = Order.objects.filter(
        user_id=request.user).order_by(
            '-forward_order_time')
    return render(request, 'pizza/my_orders.html', {'orders': orders})


@login_required
def update_pizza_quantity(request, item_id):
    """
    Updates the quantity of a pizza in the user's cart.
    **Context**
    The user must be authenticated to update the quantity
    of a pizza in their cart.
    If the order is not from today, the user is informed
    that the order cannot be updated.
    If the quantity is not a valid number or is less than
    or equal to 0, the user is informed that the
    quantity must be a valid number greater than 0.
    If the quantity is valid, the quantity is updated.
    **Template:**
    :template:`pizza/order.html`
    """
    if request.method == 'POST':
        today = timezone.now().date()
        order_item = get_object_or_404(
            OrderItem, id=item_id, order_id__user_id=request.user.id
        )

        # Check if the order is from today
        if order_item.order_id.order_date.date() != today:
            messages.error(request, 'You can only update orders from today.')
            return HttpResponseRedirect(reverse('order_url'))

        # Get the new quantity from the form
        quantity_input = request.POST.get(
            'quantity', '').strip()  # Get and strip the input
        if not quantity_input.isdigit() or int(quantity_input) <= 0:
            # Handle invalid or empty input
            messages.error(
                request,
                'Please enter a valid quantity greater than 0.'
                )
            return HttpResponseRedirect(reverse('order_url'))

        # Update the quantity if valid
        new_quantity = int(quantity_input)
        order_item.quantity = new_quantity
        order_item.save()
        messages.success(
            request,
            'The quantity has been updated successfully.'
            )

    return HttpResponseRedirect(reverse('order_url'))


def contact_us(request):
    """
    Renders a contact form for the user to submit.
    **Context**
    Allows the user to submit a contact form.
    If the form is submitted successfully, the user is
    informed that their message has been received.
    **Template:**
    :template:`pizza/contact_us.html`
    """
    if request.method == "POST":
        contactus_form = ContactUsForm(data=request.POST)
        if contactus_form.is_valid():
            contactus_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Thank you for your message. "
                                 "I endeavour to respond within "
                                 "2 working days.")

    contactus_form = ContactUsForm()

    return render(
        request,
        "pizza/contact_us.html",
        {"contactus_form": contactus_form},
    )

pizza/templates/pizza/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}PizzaMe! Contact Us Page{% endblock title %}
{% block description %}PizzaMe! - We'd love to hear from you!
{% endblock description %}
{% block keywords %}contact{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-md-4 text-center">
            <img src="{% static 'images/nobody.jpg' %}" width="75%">
        </div>
        <div class="col-12 col-md-8">
            <h2>Contact Us</h2>
            <p>We'd love to hear from you. Please fill in the form below to send us a message!</p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 my-5">
            <form method="post">
                {{ contact_us_form | crispy }}
                {% csrf_token %}
                <button class="btn btn-secondary" type="submit" name="submit button">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

pizza/templates/pizza/index.html
{% extends 'base.html' %}
{% block title %}PizzaMe! Homepage{% endblock title %}
{% block extras %}
{% endblock extras %}

{% block content %}
{% load static %}
<div class="container mt-5">
  <div class="row">
    <div class="col-4 text-center">
                
    </div>
    <div class="col-8">
      <!-- Title goes between these h2 tags -->
      <h2>This is the index page placeholder text</h2>
      <!-- Content goes directly underneath this -->
      
    </div>
  </div>
  <div class="row">
    <div class="col text-right">
      <!-- Updated on field goes in here -->

      <p class="text-end"><em>Updated on: </em></p>
    </div>
  </div>
</div>
{% endblock content %}

pizza/templates/pizza/my_orders.html
{% extends 'base.html' %}

{% block title %}My Orders{% endblock title %}
{% block description %}My Order Page, All My Orders Past and Present{% endblock %}
{% block keywords %}My Orders{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center title">My Orders</h1>
    {% if orders %}
        {% for order in orders %}
            <div class="card mb-3">
                <div class="card-header">
                    <p><span class="card-topic">Order ID:</span> {{ order.id }}</p>
                    <p><span class="card-topic">Status:</span> {{ order.status }}</p>
                    <p><span class="card-topic">Total Price:</span> £{{ order.total_price }}</p>
                    <p><span class="card-topic">Order Date:</span> {{ order.order_date }}</p>
                    {% if order.forward_order %}
                        <p><span class="card-topic">Forward Order:</span> {{ order.forward_order|yesno:"Yes,No" }}</p>
                        <p><span class="card-topic">Forward Order Time:</span> {{ order.forward_order_time }}</p>
                    {% endif %}
                </div>
                <h2 class="text-center my-orders-title">Pizzas in this order:</h2>
                <div class="my-orders-card-body">                    
                    <ul>
                        {% for item in order.orderitem_set.all %}
                            <li>
                                <img src="{{ item.pizza_id.featured_image.url }}" alt="{{ item.pizza_id.name }}" class="img-thumbnail" style="width: 100px; height: auto;" loading="lazy">
                                <strong>{{ item.pizza_id.name }}</strong> - Size: {{ item.pizza_id.size }}, Quantity: {{ item.quantity }}, Price: £{{ item.pizza_id.price }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>You have no orders.</h1>
    {% endif %}
</div>
{% endblock content %}

pizza/templates/pizza/order.html
{% extends 'base.html' %}

{% block title %}PizzaMe! Order Pizza Page{% endblock title %}
{% block description %}Order your favorite pizza from PizzaMe!{% endblock description %}
{% block keywords %}pizza, order, food, delivery{% endblock keywords %}
{% block content %}
{% load static %}

<div class="container mt-5">
  <div class="row">
    <div class="col-12 body-content">
      <!-- Title goes between these h2 tags -->
      <h1 class="text-center title">Buy a Pizza here <u>TODAY</u></h1>
      <!-- Content goes directly underneath this -->
      <div class="container-fluid">
        <div class="row">
          <!-- Pizza's Available -->
          {% if not user.is_authenticated %}
          <p class="text-center please-login">Please <a href="{% url 'account_login' %}" aria-label="Login to order pizza">login</a> to order pizza, or <a href="{% url 'account_signup' %}" aria-label="Register to create an account and order pizza">Register</a> if you are new here!</p>
          {% endif %}
          <div class="col-12 mt-3 left">
            <div class="row">
              {% for pizza in pizza_list %}
              <div class="col-md-4">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="image-container">
                      {% if "placeholder" in pizza.featured_image.url %}
                      <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image" width="368px" height="368px">
                      {% else %}
                      <img class="card-img-top" src="{{ pizza.featured_image.url }}" alt="{{ pizza.name }}" width="368px" height="368px" {% if forloop.counter > 1 %}loading="lazy"{% endif %}>
                      {% endif %}
                      <div class="image-flash">
                        <p class="Pizza">Pizza: {{ pizza.name }}</p>
                        <p class="Size">Size: {{ pizza.size }}</p>
                        <p class="Price">Price: £{{ pizza.price }}</p>
                      </div>
                    </div>                       
                    <p class="card-text">{{ pizza.description }}</p>
                    {% if user.is_authenticated %}
                      {% if cart_order %}
                        {% if order_items %}
                            <!-- If the pizza is not in the cart, show the order button -->
                            <span class="orderbutton" style="display: block;" id="OrderButton{{pizza.id}}"><a href="{% url 'order_pizza' pizza.id %}" class="btn btn-primary" aria-label="Order {{ pizza.name }} pizza">Order</a></span>
                            {% for order_item in order_items %}
                              {% if order_item.pizza_id_id == pizza.id %}
                                <!--  Hide the order button -->
                                <script> document.getElementById("OrderButton{{pizza.id}}").style.display = "none"; </script>
                                <!-- If the pizza is already in the cart, show the update and delete buttons -->
                                <form method="post" action="{% url 'update_pizza_quantity' order_item.id %}" class="d-block">
                                {% csrf_token %}
                                <span class="updatebutton"><label for="quantity{{pizza.id}}" class="me-2">Quantity:</label>
                                <input type="number" id="quantity{{pizza.id}}" name="quantity" value="{{ order_item.quantity }}" min="1" class="form-control me-2" style="width: 60px;">
                                <button type="submit" class="btn btn-secondary btn-custom-width" name="Update Order">Update</button>
                                </span></form>
                                <span class="deletebutton">
                                <a href="{% url 'delete_pizza_order' pizza.id %}" class="btn btn-danger btn-custom-width" aria-label="Delete {{ pizza.name }} pizza from your order">Delete</a>
                                </span> 
                              {% endif %}
                            {% endfor %}   
                        {% else %}
                        <!-- If there are no orders, create initial buttons -->
                        <span class="orderbutton"><a href="{% url 'order_pizza' pizza.id %}" class="btn btn-primary" aria-label="Order {{ pizza.name }} pizza">Order</a></span>
                        {% endif %}
                      {% else %}
                      <!-- If there is no cart, create initial buttons -->
                      <span class="orderbutton"><a href="{% url 'order_pizza' pizza.id %}" class="btn btn-primary" aria-label="Order {{ pizza.name }} pizza">Order</a></span>  
                      {% endif %}
                    {% endif %}        
                  </div>
                </div>
              </div>
              {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous Page">&laquo; PREV</a>
                </li>
              {% endif %}
              {% if page_obj.has_next %}
                <li>
                  <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next Page"> NEXT &raquo;</a>
                </li>
              {% endif %}
          </ul>
        </nav>
    {% endif %}
      </div> 
    </div>
  </div>
</div>
{% endblock content %}